#! /bin/sh
rm Run.Main
cd /mnt/hgfs/SDT
rm Run.Main
echo "---------------------------------------------------------"
rm Makefile
cp ./SettingFile-Linux/Makefile-DM Makefile
make
echo "---------------------------------------------------------"
cp Run.Main /home/leifwen/work/SDT
cd /home/leifwen/work/SDT
sudo ./Run.Main
