//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SDT.rc
//
#define IDD_DEVLIST                     101
#define IDP_OLE_INIT_FAILED             111
#define IDP_FAILED_TO_CREATE            112
#define IDB_MAIN                        113
#define IDB_MENU_IMAGES_24              114
#define ID_WINDOW_MANAGER               115
#define IDR_MAINFRAME                   116
#define IDR_SDTTYPE                     117
#define IDR_MENU_IMAGES                 118
#define IDR_POPUP_EDIT                  119
#define IDR_THEME_MENU                  120
#define IDS_EDIT_MENU                   121
#define ID_CANCEL_EDIT_CNTR             122
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_VIEW_SCVIEW                  310
#define ID_VIEW_GCVIEW                  311
#define ID_VIEW_GCPROPERTIESVIEW        312
#define ID_VIEW_GCCOMVIEW               313
#define ID_VIEW_SCOKETVIEW              314
#define ID_VIEW_SENDVIEW                315
#define ID_VIEW_CALCVIEW                316
#define IDI_SCWND                       400
#define IDI_GCWND                       401
#define IDI_GCPWND                      402
#define IDI_GCCOMMAND                   403
#define IDI_MCFRM                       404
#define IDI_SOCKETFRM                   405
#define IDI_SENDWND                     406
#define IDI_CALC                        407
#define IDR_TOOLBAR_SC                  450
#define IDR_TOOLBAR_GC                  451
#define IDR_TOOLBAR_PROPERTIES          452
#define IDR_TOOLBAR_DL                  453
#define IDR_TOOLBAR_SOCKET              454
#define IDR_POPUP_SC                    455
#define IDR_POPUP_GC                    456
#define IDR_RIBBON                      500
#define IDB_RI_BUTTONS                  501
#define IDB_RI_LARGE                    502
#define IDB_RI_SMALL                    503
#define IDB_RI_LARGE_CMUX               504
#define IDB_RI_SMALL_CMUX               505
#define IDB_SCViewBarButton_hc          506
#define IDB_GCViewBarButton_hc          507
#define IDB_PROPERTIES_HC               508
#define IDB_SOCKET_HC                   509
#define IDB_DLBarButton_hc              510
#define ID_RI_COMBO_COM                 32800
#define ID_RI_COMBO_BR                  32801
#define ID_RI_CHECK_DSR_FLOW            32802
#define ID_RI_CHECK_CTS_FLOW            32803
#define ID_RI_CHECK_DTR_HIGH            32804
#define ID_RI_CHECK_DTR_LOW             32805
#define ID_RI_CHECK_RTS_HIGH            32806
#define ID_RI_CHECK_RTS_LOW             32807
#define ID_RI_CHECK_ASCII               32808
#define ID_RI_CHECK_HEX                 32809
#define ID_RI_CHECK_VIEW                32810
#define ID_RI_CHECK_OSPMSG              32811
#define ID_RI_CHECK_MSR                 32812
#define ID_RI_CHECK_RECMSG              32813
#define ID_RI_BUTTON_CONNECT            32814
#define ID_RI_BUTTON_ECHO               32815
#define ID_RI_BUTTON_DEVLIST            32816
#define ID_RI_BUTTON_SOCKETLIST         32817
#define ID_RI_BUTTON_SPRIPT_STOP        32818
#define ID_RI_BUTTON_SCRIPT_AT          32819
#define ID_RI_BUTTON_SCRIPT_CE          32820
#define ID_RI_BUTTON_SC                 32821
#define ID_RI_BUTTON_GC                 32822
#define ID_RI_BUTTON_CLEANVIEW          32823
#define ID_RI_BUTTON_OPENRFD            32824
#define ID_RI_BUTTON_NEWRECORD          32825
#define ID_RI_BUTTON_SEND               32826
#define ID_RI_BUTTON_CALC               32827
#define ID_RI_COMBO_AUXCOM              32828
#define ID_RI_COMBO_AUXBR               32829
#define ID_RI_BUTTON_AUXOPEN            32830
#define ID_RI_CHECK_AUXDTRH             32831
#define ID_RI_CHECK_AUXDTRL             32832
#define ID_RI_CHECK_AUXRTSH             32833
#define ID_RI_CHECK_AUXRTSL             32834
#define ID_RI_CHECK_AUXESCAPE           32835
#define ID_RI_CHECK_AUXHEX              32836
#define ID_RI_CHECK_AUXASCII            32837
#define ID_RI_CHECK_AUXDSR              32838
#define ID_RI_CHECK_AUXCTS              32839
#define ID_RI_CMUX_START                32840
#define ID_RI_CMUX_START1               32841
#define ID_RI_CMUX_CLD                  32842
#define ID_RI_CMUX_STDPSC               32843
#define ID_RI_CMUX_PSC0                 32844
#define ID_RI_CMUX_PSC1                 32845
#define ID_RI_CMUX_PSC7                 32846
#define ID_RI_CMUX_PSC9                 32847
#define ID_RI_CMUX_FC                   32848
#define ID_RE_SAVE                      32849
#define ID_RI_LICENSE                   32850
#define ID_STATUSBAR_PB                 32990
#define ID_STATUSBAR_NONE               32991
#define ID_STATUSBAR_RX                 32992
#define ID_STATUSBAR_TX                 32993
#define ID_STATUSBAR_CTS                32994
#define ID_STATUSBAR_DSR                32995
#define ID_STATUSBAR_RING               32996
#define ID_STATUSBAR_DCD                32997
#define ID_STATUSBAR_GETIP              32998
#define ID_STATUSBAR_IP                 32999
#define ID_TOOLBAR_SC_ADD               33000
#define ID_TOOLBAR_SC_DEL               33001
#define ID_TOOLBAR_SC_UP                33002
#define ID_TOOLBAR_SC_DOWN              33003
#define ID_TOOLBAR_SC_COLLAPSE          33004
#define ID_TOOLBAR_SC_EXPAND            33005
#define ID_TOOLBAR_SC_LOAD              33006
#define ID_TOOLBAR_SC_IMPORT            33007
#define ID_TOOLBAR_SC_SAVE              33008
#define ID_TOOLBAR_GC_ADD               33009
#define ID_TOOLBAR_GC_DEL               33010
#define ID_TOOLBAR_GC_UP                33011
#define ID_TOOLBAR_GC_DOWN              33012
#define ID_TOOLBAR_GC_COLLAPSE          33013
#define ID_TOOLBAR_GC_EXPAND            33014
#define ID_TOOLBAR_GC_LOAD              33015
#define ID_TOOLBAR_GC_IMPORT            33016
#define ID_TOOLBAR_GC_SAVE              33017
#define ID_TOOLBAR_GC_EDIT              33018
#define ID_TOOLBAR_GC_RUN               33019
#define ID_TOOLBAR_GC_STOP              33020
#define ID_TOOLBAR_GCP_EXPAND           33021
#define ID_TOOLBAR_GCP_SORT             33022
#define ID_TOOLBAR_GCP_COMMAND          33023
#define ID_TOOLBAR_SOCKET_DISCONNECT    33024
#define ID_TOOLBAR_DL_ADD               33025
#define ID_TOOLBAR_DL_DEL               33026
#define ID_TOOLBAR_DL_UP                33027
#define ID_TOOLBAR_DL_DOWN              33028
#define ID_TOOLBAR_DL_LOAD              33029
#define ID_TOOLBAR_DL_IMPORT            33030
#define ID_TOOLBAR_DL_SAVE              33031
#define ID_TOOLBAR_DL_REFRESH           33032
#define ID_SENDBOX_HEX                  33100
#define ID_SENDBOX_ESCAPE               33101
#define ID_SENDBOX_CR                   33102
#define ID_SENDBOX_ENABLE               33103
#define ID_SENDBOX_SEND                 33104
#define ID_CALCBOX_HEX                  33105
#define ID_CALCBOX_ESCAPE               33106
#define ID_CALCBOX_LENGTH               33107
#define ID_CALCBOX_H2A                  33108
#define ID_CALCBOX_A2H                  33109
#define ID_CALCBOX_XOR                  33110
#define ID_CALCBOX_OSP                  33111
#define ID_CALCBOX_CALC                 33112
#define ID_CMUXCTRL_DSR                 33113
#define ID_CMUXCTRL_CTS                 33114
#define ID_CMUXCTRL_DCD                 33115
#define ID_CMUXCTRL_RING                33116
#define ID_CMUXCTRL_DTR                 33117
#define ID_CMUXCTRL_RTS                 33118
#define ID_CMUXCTRL_HEX                 33119
#define ID_CMUXCTRL_ESCAPE              33120
#define ID_CMUXCTRL_OPEN                33121
#define ID_CMUXCTRL_COM                 33122
#define ID_CMUXCTRL_BR                  33123
#define ID_BUTTON2                      34000
#define ID_RI_BUTTON_SCRIPT_SHOWSBIC    34000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         34008
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           600
#endif
#endif
